### ISSUE TITLE
Autosave game data when dos writes to file 

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#238] opened 2022-07-22 21:49 UTC
Hi,

Currently, after saving a game, I need to click on the jsdos 'disk' icon in order to save the game data to browser cache.
 If I forget to click on this "disk" icon and refresh/close browser, it doesn't save my game.

 On your documents you've wrote that we should add this js line in order for the auto-save to work:
await dos.layers.save()

Now I've added this code, but it doesn't work.
Can you please publish the full working script code that will enable the js auto-save?

Thanks in advance 
Shay

**Comment by caiiiycuk** [comment] 2022-07-23 01:51
Hi. There is no documentation about auto-save feature. You mentioned docs about triggering save not about auto-save.

**Comment by caiiiycuk** [comment] 2022-07-23 01:52
Closed as duplicate of #194

**Closed as completed by caiiiycuk** 2022-07-23 01:52 UTC
