### ISSUE TITLE
 Feature Request: More buttons to virtual keyboard

### ISSUE THREAD

**Issue by sounddrill31** [caiiiycuk/js-dos.com#324] opened 2024-07-18 08:48 UTC
It'd be great if someone could add Double Quote, = and Add buttons to the keyboard, quite helpful in turbo C++

Reposted from [here](https://github.com/js-dos/repository/issues/16)

**Comment by caiiiycuk** [comment] 2024-08-29 14:44
Now you can redesing keyboard: https://js-dos.com/virtual-keyboard.html

But double quotes still not working...

**Comment by caiiiycuk** [comment] 2024-08-29 14:44
closing this as duplicate of #325

**Closed as completed by caiiiycuk** 2024-08-29 14:44 UTC
