### ISSUE TITLE
This is a report on the results of testing jsdos v8.x.

### ISSUE THREAD

**Issue by skyksit** [caiiiycuk/js-dos.com#295] opened 2023-10-19 19:36 UTC
An error occurs when setting Windows 3.1 memsize=256 in the jsdos v8.x version. 
When I set memsize=16, the error disappeared.

https://github.com/caiiiycuk/js-dos/blob/93393d929f9fd2df0574f63b6597796cc7c57b0d/src/frame/editor/defaults.ts#L332C1-L332C12

[Windows 3.1]
I installed the Korean version of Windows 3.1 and the English version of Windows 3.1, and the installation went well and the game ran well.

[PC98]
When booting in PC98 mode, there is a 10% chance that PC98 mode will run. 
=> Games for PC98 did not run.

[Windows 95]
Windows 95 OSR2.5 installation works well, but if you change the setting to high color after updating the graphics driver (S3), the screen colors do not appear properly.
=> Games that require lower resolutions run fine. But, Games that require high resolution did not run.

Thank you for the great service

**Comment by citee520** [comment] 2023-10-31 06:00
I am experiencing the same issue with Win95 in "high color (16-bit)" mode. I have installed "dosbox-x-v2023.10.06" on my PC with the same "win95.img," and the issue is not present in the PC's Dosbox-X. I suspect it is an emulator-related problem, but I am unable to test it as I cannot find version "0.80.19."

**Comment by caiiiycuk** [comment] 2023-10-31 07:37
Thank you for reporting. v8 is still under development, and probably this problems will be fixed on release.

**Comment by caiiiycuk** [comment] 2024-08-29 14:46
v8.1.19 colors are correct now

**Closed as completed by caiiiycuk** 2024-08-29 14:46 UTC
Labels: enhancement
