### ISSUE TITLE
Error: Network error, can't download bundle.jsdos

### ISSUE THREAD

**Issue by sluke817** [caiiiycuk/js-dos.com#219] opened 2022-05-10 18:23 UTC

**Comment by sluke817** [comment] 2022-05-10 18:23
Also paired with Uncaught (in promise) Error: Network error, can't download bundle.jsdos

**Comment by caiiiycuk** [comment] 2022-05-11 00:22
Again, errors like this is about wrong webserver configuration. The problem happened in network, you website didn’t serve bundle.jsdos on given url. See browser dev tools network tab. Please read documentation of jsdos or use npx create-dosbox to bootstrap project. I am closing this because it’s not a bug.

**Closed as completed by caiiiycuk** 2022-05-11 00:22 UTC
