### ISSUE TITLE
Uncaught (in promise) Error: Unable to download 'js-dos/wdosbox.js', code: 0

### ISSUE THREAD

**Issue by sluke817** [caiiiycuk/js-dos.com#218] opened 2022-05-10 17:16 UTC
![image](https://user-images.githubusercontent.com/82904475/167685398-94891230-51be-4e2b-b23d-763c2b4d883b.png)

**Comment by caiiiycuk** [comment] 2022-05-10 17:24
Duplicate of #217

**Closed as completed by caiiiycuk** 2022-05-10 17:24 UTC
